[workspace]
members = ["common", "master", "worker"]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1", features = [
    "sync",
    "macros",
    "io-util",
    "rt",
    "time",
] }
actix-web = "4.9.0"
anyhow = "1"
uuid = { version = "1.0", features = ["v4"] }
thiserror = "2.0.9"
