[package]
name = "worker"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
reqwest = { version = "0.12.9", features = ["json"] }
serde = { workspace = true }
tokio = { version = "1", features = ["full"] }
dotenv = { workspace = true }
envy = { workspace = true }
